ELZT-72: initial commit of CapabilityStatement for the use case refer…
Nictiz/Nictiz-R4-ELZ pull request #17
Opened 2023-05-23 18:55 UTC by niekvangalen

…ral from general practitioner to allied health professional

2023-05-23 18:57 UTC, niekvangalen commented
@LuudSlagter this is a first approach for a minimum CapabilityStatement for both client and server, what do you think?

2023-05-24 08:12 UTC, LuudSlagter requested changes

2023-05-25 11:25 UTC, niekvangalen commented on CapabilityStatements/hg-Referral-GeneralPractitionerToAlliedHealthProfessional.xml
> +                <code value="search-type"/>
No, not yet. Good point.

2023-05-25 11:27 UTC, niekvangalen commented on CapabilityStatements/hg-Referral-GeneralPractitionerToAlliedHealthProfessional.xml
> +            <interaction>
Fixed.

2023-05-25 11:27 UTC, niekvangalen commented on CapabilityStatements/hg-Referral-GeneralPractitionerToAlliedHealthProfessional.xml
> +            <profile>
Fixed.

2023-05-25 11:27 UTC, niekvangalen commented on CapabilityStatements/hg-Referral-GeneralPractitionerToAlliedHealthProfessional.xml
> +    <documentation value="Minimal requirements for a client to fulfill the 'Referral from general practitioner to allied health professional' usecase (system role: HZP-VPS)."/>
Fixed.

2023-05-25 11:37 UTC, niekvangalen commented on CapabilityStatements/hg-Referral-GeneralPractitionerToAlliedHealthProfessional.xml
> +            <interaction>
I'm gonna leave search-type and read in here for now, to support future use cases.

2023-05-25 11:44 UTC, niekvangalen commented
@LuudSlagter I processed your comments, can you take another look?

2023-05-25 14:13 UTC, LuudSlagter approved these changes

2023-05-25 14:21 UTC, merged