Nictiz 1669: add Task examples
Nictiz/Nictiz-R4-ELZ pull request #19
Opened 2023-06-27 12:09 UTC by niekvangalen

2023-07-05 14:14 UTC, NictizEduard commented
@LuudSlagter  Could you please review our changes?

2023-07-06 14:02 UTC, LuudSlagter requested changes

2023-07-06 14:02 UTC, LuudSlagter commented on examples/hg-ReferralComposition-01.xml
> +                    <display value="vertaling toelichting op aard van verwijzing (waarneembare entiteit)"/>
Use 'toelichting op aard van verwijzing (waarneembare entiteit)' or 'toelichting op aard van verwijzing' (I'd prefer the latter).

2023-07-06 14:02 UTC, LuudSlagter commented on examples/hg-ReferralComposition-01.xml
> +                    <display value="toelichting op voorgesteld beleid (waarneembare entiteit)"/>
Suggestion: just use 'toelichting op voorgesteld beleid'.

2023-07-06 14:02 UTC, LuudSlagter commented on examples/hg-ReferralTask-02.xml
> +        <dateTime value="2023-06-22"/>
This date should be aligned with the ServiceRequest and Composition.

2023-07-06 14:02 UTC, LuudSlagter commented on examples/hg-ReferralTask-01.xml
> +        <dateTime value="2023-06-22"/>
This date should be aligned with the ServiceRequest and Composition.

2023-07-07 06:28 UTC, LuudSlagter requested changes

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-01.xml
> -            <type value="PractitionerRole"/>
This line should be restored again, in line with other references ;)

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-02.xml
> -            <type value="PractitionerRole"/>
See other example.

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-01.xml
> +            <reference value="PractitionerRole/hg-ReferralServiceRequest-01-PractitionerRole-01"/>
Change indentation of these two lines.

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-02.xml
> +            <reference value="PractitionerRole/hg-ReferralServiceRequest-02-PractitionerRole-01"/>
Change indentation of these two lines.

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-02.xml
> +    <focus>
Add `. type`.

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-02.xml
> +    <for>
Add `. type`.

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-02.xml
> +    <requester>
Add `. type`.

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-01.xml
> +    <focus>
Add `. type`.

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-01.xml
> +    <for>
Add `. type`.

2023-07-07 06:28 UTC, LuudSlagter commented on examples/hg-ReferralTask-01.xml
> +    <requester>
Add `. type`.

2023-07-10 10:15 UTC, LuudSlagter approved these changes

2023-07-10 12:14 UTC, merged